# Generated by Django 2.0.5 on 2018-06-02 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('capacidadecarga', models.IntegerField()),
                ('autonomia', models.IntegerField()),
                ('capacidadepassageiros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50, null=True)),
                ('numero', models.IntegerField(blank=True)),
                ('cep', models.IntegerField(blank=True)),
                ('complemento', models.CharField(max_length=50, null=True)),
                ('bairro', models.CharField(max_length=50, null=True)),
                ('cidade', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poltrona', models.IntegerField()),
                ('datap', models.DateField()),
                ('horariop', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('cpf', models.IntegerField(blank=True)),
                ('telefonecel', models.IntegerField(blank=True)),
                ('telefone', models.IntegerField(blank=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracaovoo', models.IntegerField()),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gerenciar.Aeronave')),
                ('chegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chegada', to='Gerenciar.Aeroporto')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saida', to='Gerenciar.Aeroporto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Gerenciar.Pessoa')),
                ('passaporte', models.IntegerField(blank=True)),
            ],
            bases=('Gerenciar.pessoa',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Gerenciar.Pessoa')),
                ('nit', models.IntegerField()),
                ('salario', models.IntegerField()),
                ('dataentrada', models.DateField()),
                ('datasaida', models.DateField()),
            ],
            bases=('Gerenciar.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gerenciar.Endereco'),
        ),
        migrations.AddField(
            model_name='passagem',
            name='voo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gerenciar.Voo'),
        ),
        migrations.AddField(
            model_name='aeroporto',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gerenciar.Endereco'),
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Gerenciar.Funcionario')),
                ('breve', models.IntegerField()),
                ('horasdevoo', models.IntegerField()),
            ],
            bases=('Gerenciar.funcionario',),
        ),
        migrations.AddField(
            model_name='passagem',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gerenciar.Cliente'),
        ),
        migrations.AddField(
            model_name='voo',
            name='piloto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gerenciar.Piloto'),
        ),
    ]
